### ISSUE TITLE
Fatal Exception: java.lang.SecurityException: Binder invocation to an incorrect interface

### ISSUE THREAD

**Issue by Kobreizhyashi** [openid/AppAuth-Android#1035]
A QA tester is facing an error which I can't reproduce, a crash when trying to connect : 

```
Fatal Exception: java.lang.SecurityException: Binder invocation to an incorrect interface
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
       at android.os.Parcel.createException(Parcel.java:2995)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.os.Parcel.readException(Parcel.java:2920)
       at android.support.customtabs.ICustomTabsService$Stub$Proxy.warmup(ICustomTabsService.java:270)
       at androidx.browser.customtabs.CustomTabsClient.warmup(CustomTabsClient.java:223)
       at net.openid.appauth.browser.CustomTabManager$1.onCustomTabsServiceConnected(CustomTabManager.java:84)
       at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2251)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2284)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8227)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

He's using a Redmi note 10 5G with google chrome as default browser. 

We didn't whitelist/blacklist any browser and I had read the issue with a similar problem but nobody use Yandex here : https://github.com/openid/AppAuth-Android/issues/672

have you ever faced the same issue ? 

Regards,

**Comment by Kobreizhyashi** [comment]
We reproduced the bug on a google pixel 6A also

**Comment by Kobreizhyashi** [comment]
Resolved with : 

`
# AppAuth
-keep class android.support.customtabs.** { *; }
`
