### ISSUE TITLE
android.content.ActivityNotFoundException: When app opened

### ISSUE THREAD

**Issue by dhruvsunking** [openid/AppAuth-Android#1052]
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.11.1
- Integration: Java/Kotlin

### Issue Description

**Get this exception on Crashlytics when app is opened**

```
Caused by android.content.ActivityNotFoundException:
       at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:555)
       at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:390)
       at login.utils.LoginHelper.doAuth(LoginHelper.java:131)
       at login.utils.LoginHelper.startAuth(LoginHelper.java:112)
       at login.view.LoginHomeActivity.startAuth(LoginHomeActivity.kt:196)
       at login.view.LoginHomeActivity.initView(LoginHomeActivity.kt:118)
       at baseclass.BaseActivity.onCreate(BaseActivity.kt:42)
       at android.app.Activity.performCreate(Activity.java:8591)
       at android.app.Activity.performCreate(Activity.java:8570)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by CompileConnected** [comment]
can you explain more?
is it minify? if does, you might need to exclude the app auth library to be obsfucate by gradle

**Comment by amit517** [comment]
Hi from Android 13 we are required to add `category` with the intent. If didn't have that with your intent, can you add the following and check if that helps.

`
 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
            authIntent.addCategory(Intent.CATEGORY_DEFAULT)
            authIntent.addCategory(Intent.CATEGORY_BROWSABLE)
        }
`

**Comment by JaFiOriflame** [comment]
We have the same problem. We implemented it recently. Successfully tested on multiple devices. However, after we've released it we have a lot of ActivityNotFoundException. Mostly Samsung devices and Android 13. Unfortunately, I don't have any device with this problem :-(

![image](https://github.com/openid/AppAuth-Android/assets/155519974/aff123cb-20c1-4092-bcd9-317b75c63a1a)

**Comment by guillaume-tgl** [comment]
I also had several users reporting this problem, all with Samsung devices with Android 13. And the problem goes away after restarting the device. It seems like there's a bug with intent handling on this version of Samsung-modified Android version.
Seems related to this SO question: https://stackoverflow.com/questions/78341069/packagemanager-queryintentactivities-returns-empty-on-random-devices

**Comment by W-quan** [comment]
<img width="848" alt="图片" src="https://github.com/openid/AppAuth-Android/assets/9608466/7a1ed226-fcdb-4eef-898b-b29ca2b23e8f">
<img width="600" alt="图片" src="https://github.com/openid/AppAuth-Android/assets/9608466/1969a62a-ca81-441c-a267-b41960aa5864">
<img width="586" alt="图片" src="https://github.com/openid/AppAuth-Android/assets/9608466/e3daec8c-ca7d-4a9a-8736-99653dbbff98">

**Comment by uitstu** [comment]
<img width="557" alt="Screen Shot 2024-09-23 at 09 25 44" src="https://github.com/user-attachments/assets/a3803e15-573d-456e-9c67-cbc4890524b4">

@guillaume-tgl not only Android 13, not only Samsung, hope you all fix this bug on next version

**Comment by svenjacobs** [comment]
Also seeing the same crashes in Firebase Crashlytics but can't reproduce it.

Also see issue #991 with some interesting information: It might be related to Samsung Internet Browser installed from the Galaxy Store.

**Comment by wnetsimon** [comment]
Is there any solution to this yet?

Some of our users face the same issue with Samsung (Android 13) devices - they suddenly get an ActivityNotFoundException in prepareAuthorizationRequestIntent, even though there are browsers installed on the device.

**Comment by SunnyBe** [comment]
@rprunskas do you mind sharing a github gist for how you implemented your workaround?

**Comment by SunnyBe** [comment]
@guillaume-tgl did you find any fix or workaround, kindly share with me

**Comment by rprunskas** [comment]
> @rprunskas do you mind sharing a github gist for how you implemented your workaround?

Sorry, I can't provide code as it isn't open source. But the main idea is to use webview instead of browser. And I could confirm that this workaround solves this issue(it might not work if auth provider doesn't support webview).

**Comment by svenjacobs** [comment]
> But the main idea is to use webview instead of browser.

I think AppAuth doesn't use the `WebView` for a reason, because a `WebView` might be outdated on a smartphone and also `WebViews` allow injecting JavaScript code from the app side. I think these are good reasons to not use a `WebView` for a security critical process like authentication.

**Comment by rprunskas** [comment]
> > But the main idea is to use webview instead of browser.
> 
> I think AppAuth doesn't use the `WebView` for a reason, because a `WebView` might be outdated on a smartphone and also `WebViews` allow injecting JavaScript code from the app side. I think these are good reasons to not use a `WebView` for a security critical process like authentication.

Yes, I agree. Many of our users experienced this issue, so I had to do workaound for them only.

**Comment by MarcDahlem** [comment]
The problem still exists...
Does someone have new insights, why this is happening?
In our case it's only Samsung Android 13.
Do other vendor implementations, which were initially forked from appauth, have solutions and workarounds others than using WebViews?
