### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: net.openid.appauth.browser.CustomTabManager

### ISSUE THREAD

**Issue by kamil-cakir** [openid/AppAuth-Android#1085]
### Checklist:

- [X] I am using the latest release
- [X] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [X] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ ] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.11.1
- Integration: Native Java/Kotlin
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

### Issue Description
In our firebase crash logs we see a crash report like below.

```          
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: net.openid.appauth.browser.CustomTabManager$1@1b8d1f9
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at net.openid.appauth.browser.CustomTabManager.dispose(CustomTabManager.java:124)
```

We use latest version of the library.

```    
implementation 'net.openid:appauth:0.11.1'
```

What is the reason for this problem?

**Comment by kamil-cakir** [comment]
Is there anyone facing with this issue?

**Comment by RomanPolach** [comment]
Yeah, i have the same issue. But i dont think we will hear from the authors of the library, this shit was not updated many years.
