### ISSUE TITLE
AuthorizationService checking for browser at init time

### ISSUE THREAD

**Issue by mattinger** [openid/AppAuth-Android#113]
AuthorizationService is checking for an installed browser at initialization time.  I'm thinking this should probably be delayed until you actually need it.  It's possible the user logged in and then disabled their browser (yeah, i know), and you can't use AuthorizationService to refresh tokens, even though you don't need the browser at that point.

`Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.support.customtabs.action.CustomTabsService }
                                                                             at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1209)
                                                                             at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1308)
                                                                             at android.app.ContextImpl.bindService(ContextImpl.java:1286)
                                                                             at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
                                                                             at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
                                                                             at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:64)
                                                                             at net.openid.appauth.BrowserHandler.bindCustomTabsService(BrowserHandler.java:86)
                                                                             at net.openid.appauth.BrowserHandler.<init>(BrowserHandler.java:61)
                                                                             at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:101)`

**Comment by iainmcgin** [comment]
The intention here is to warm up custom tab supporting browsers early, to
minimize the delay in starting the authorization flow. However, the absence
of a browser should not prevent construction of AuthorizationService so
this is definitely a bug that I'll fix.

Still, this seems pretty rare. Why would a user disable all browsers on
their device? How would one expect to use OAuth without a browser? Is your
use case actually some headless device that has been supplied a refresh
token through some other means?

**Comment by mattinger** [comment]
Our use case is out QA will do this. They routinely disable supporting apps to see if it will crash :(

**Comment by iainmcgin** [comment]
OK, I'll submit a fix anyway. It will just push the error to the point at which you attempt to authorize, as there's genuinely nothing we can do about no browser existing then :)

**Comment by mattinger** [comment]
just curious when we might expect to see this in a released version (ie. 0.4.0 perhaps).

**Comment by iainmcgin** [comment]
Yes, I'm planning to get this in to 0.4.0. I have a change I'll be pushing today to support browser whitelisting, and a follow up change to make browser warm-up optional. I'll get it our ASAP.

**Comment by mattinger** [comment]
Thanks. Any eta for 0.4.0?

**Comment by iainmcgin** [comment]
I'm aiming to have it out before the end of this week.

**Comment by iainmcgin** [comment]
#119 will no longer try to initialize the warmup service for a browser, if no suitable browser available. So from 0.4.0 this should no longer cause you an issue.
