### ISSUE TITLE
RedirectUri doesn't work after I forked the project.

### ISSUE THREAD

**Issue by Smao0875** [openid/AppAuth-Android#171]
Hi guys, I might need some help here.
At first I referenced this library by using:
compile 'net.openid:appauth:0.5.1' in my gradle file.
the RedirectUriReceiverActivity in AndroidManifest.xml looks like:
data android:scheme="${appAuthRedirectScheme}" -- I only put the scheme part here.

Then I declared:
manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.googleusercontent.apps.Client_ID'
        ]
in my gradle file. Everything works fine.

However, after I forked this project and put "net.openid.appauth" code in a library module in my own project it didn't work anymore.
I tried using : data android:scheme="com.myapp"
Still didn't work.

My google authentication stops at CustomTabActivity.

Any suggestions?
Much appreciated.

Thanks.

**Comment by Smao0875** [comment]
Here is how my library gradle file looks like:

apply plugin: 'com.android.library'

android {
    compileSdkVersion 24
    buildToolsVersion "23.0.2"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 24
    }
}

android.buildTypes.debug.manifestPlaceholders = [
        'appAuthRedirectScheme': 'net.openid.appauth.test'
];

dependencies {
    compile 'com.android.support:customtabs:24.2.1'
}

apply from: "${rootProject.projectDir}/config/gradle/libraryName.gradle"
apply from: "${rootProject.projectDir}/config/gradle/checkstyle.gradle"

I put
manifestPlaceholders = [
'appAuthRedirectScheme': 'com.googleusercontent.apps.Client_ID'
]
in the gradle file of the module which depended on library(appauth) module.

Thanks for the help.

**Comment by Smao0875** [comment]
The other thing I changed is that I removed a line from AndroidManifest.xml:
android:launchMode="singleTask"

I think it won't affect the redirect.

Thanks.

**Comment by iainmcgin** [comment]
Can you show us what the `<activity>` element looks like for RedirectUriReceiverActivity in your app's generated manifest? It should look something like:

```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="YOUR_CLIENT_ID"/>
  </intent-filter>
</activity>
```

Also ensure that the redirect URI you are using in `AuthorizationRequest` matches this scheme.

Also, see [this comment](https://github.com/openid/AppAuth-Android/issues/164#issuecomment-278768826) on a similar issue for more information.

**Comment by Smao0875** [comment]
@iainmcgin 
Thanks very much for the quick reply.

I am sorry that I didn't know where to find my app's generated Manifest, 
What I did is extracting AndroidManifest.xml from my apk file and got such:
 E: activity (line=1213)
          A: android:name(0x01010003)="net.openid.appauth.RedirectUriReceiverActivity" (Raw: "net.openid.appauth.RedirectUriReceiverActivity")
          A: android:exported(0x01010010)=(type 0x12)0xffffffff
          E: intent-filter (line=1216)
            E: action (line=1217)
              A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
            E: category (line=1219)
              A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
            E: category (line=1220)
              A: android:name(0x01010003)="android.intent.category.BROWSABLE" (Raw: "android.intent.category.BROWSABLE")
            E: data (line=1222)
              A: android:scheme(0x01010027)="com.googleusercontent.apps.251872091425-***secret***fn5l" (Raw: "com.googleusercontent.apps.251872091425-***secret***fn5l")

When I was making auth request, I get my redirectUri by dumping all my activities and get the intent for CustomTabActivity:
dat=https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=com.googleusercontent.apps.251872091425-***secret***fn5l%3A%2Foauth2redirect

So I can assume I am doing right. Sounds right?

BTW: Is there any thing I should be careful when fork your project?
What I did is:
1. Create a module called "library" in my app.
2. Copy the "library" code from your project into my "library"
3. Change the gradle file in "library" to the file shown above.
4. Create dependency between my app and "library" module.
5. Got such result above.

Thanks again.

**Comment by iainmcgin** [comment]
The manifest appears to contain what it needs from the output you included, and it also looks like the authorization request is correct. You can test that your app is handling the redirect URI you expect by running:

```
adb shell am start -W \
    -a android.intent.action.VIEW \
    -c android.intent.category.DEFAULT \
    -d REDIRECT_URI
```

If that doesn't start your app (and likely crash, because you are doing it out of context) then the issue is with the manifest. If that works, then the issue lies with issuing the redirect from the custom tab, which could be a configuration issue with your client ID.

The simplest steps to copy the library to your app would be to copy the entire library/ folder of this repository into your app, and then modify your "settings.gradle" to include ":library". That would at least give you a baseline where you haven't changed anything, and haven't forgotten to copy anything. You shouldn't have to modify the library.gradle at all.

Have you tried using your client ID with the demo app? Does that also fail?

P.S. For reference, you can usually find the generated manifest in `build/intermediates/manifests/full/<build_variant>/AndroidManifest.xml`.

**Comment by Smao0875** [comment]
@iainmcgin 
Thanks.

I tried building my app without forking locally.
App works fine.
However, when I tried invoking my app using command line:
adb shell am start -W \
    -a android.intent.action.VIEW \
    -c android.intent.category.DEFAULT \
    -d com.googleusercontent.apps.251872091425-secretfn5l
I got error message:
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=com.googleusercontent.apps.251872091425-secretfn5l flg=0x10000000 }

Does this mean I never got it right?

Thanks.

**Comment by iainmcgin** [comment]
Based on your output I'm not sure if you passed a full redirect URI, e.g. scheme:target. Looks like you only included the scheme (unless that is being redacted by Android, I can't remember the exact behavior here).

**Comment by iainmcgin** [comment]
I think you should consider your architecture more carefully too; I don't think it makes sense to split the functioning of AppAuth across different apps (based on your description in #170) - pick a host app and run the entire flow from within it. From your description you have an app which is responsible for adding Google accounts - that is the app that I believe should be responsible for running the entire flow, with the other app requesting account addition through a simpler, higher-level API.

**Comment by Smao0875** [comment]
Still didn't work after removed line:
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
from AuthorizationManagementActivity.createResponseHandlingIntent().

My current activity stack looks like:
Run #6: ActivityRecord{71e972a u0 com.serviceApp/net.openid.appauth.AuthorizationManagementActivity t149}
        Run #5: ActivityRecord{c09b10f u0 com.serviceApp/net.openid.appauth.RedirectUriReceiverActivity t149 f}
        Run #4: ActivityRecord{fd6cd4a u0 com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity t142}
        Run #3: ActivityRecord{8cbf62c u0 com.serviceApp/net.openid.appauth.AuthorizationManagementActivity t142}
        Run #2: ActivityRecord{e04f582 u0 com.serviceApp/com.serviceApp.OAuthActivity t142}
        Run #1: ActivityRecord{ed280b3 u0 com.serviceApp/com.serviceApp.AccountSetup t142}
        Run #0: ActivityRecord{9a67c47 u0 com.uiApp/.ui.MainActivity t142}

Seems I am in a dead loop....

I think other users will encounter the same issue if their app is going to handle adding Google account from Android Settings, the activity will be like following: 
Task1: (Anroid OS) Settings -> (Anroid OS) SubSettings -> (Anroid OS) SubSettings ->(User's app) AccountSetup -> (User's app) OAuthActivity
Task2: AuthorizationManagementActivity -> CustomTabActivity
Because:
1. the taskAffinity of AuthorizationManagementActivity will be as same as user's app.(It's launched from user's app), so it is different from the root activity of Task1 (Settings).
2. the singleTask property of AuthorizationManagementActivity.

Am I correct?
Thanks.

**Comment by Smao0875** [comment]
@iainmcgin 
Thanks for your opinion and I totally agree with you.

The situation is that we are maintaining a huge code base here and it might take great effort to re-architect the apps.
Anyway I will talk to my team to see if there is anything we can do.
Thanks again.

Btw, could you please take a look at the situation I mentioned above?

"I think other users will encounter the same issue if their app is going to handle adding Google account from Android Settings, the activity will be like following:
Task1: (Anroid OS) Settings -> (Anroid OS) SubSettings -> (Anroid OS) SubSettings ->(User's app) AccountSetup -> (User's app) OAuthActivity
Task2: AuthorizationManagementActivity -> CustomTabActivity
Because:

the taskAffinity of AuthorizationManagementActivity will be as same as user's app.(It's launched from user's app), so it is different from the root activity of Task1 (Settings).
the singleTask property of AuthorizationManagementActivity.
Am I correct?"

**Comment by iainmcgin** [comment]
Sorry, it's been a busy week, do you still need help with this? After you mentioned android settings and account manager, I think I understand your use case a little better - are you implementing an [authenticator](https://developer.android.com/reference/android/accounts/AbstractAccountAuthenticator.html) that adds accounts to [AccountManager](https://developer.android.com/reference/android/accounts/AccountManager.html), and having other client apps trigger authentication flows for that authenticator?

Is it possible for you to have app A launch an activity in app B, passing an AuthorizationRequest in the data bundle, and have app B then create an AuthorizationService and trigger performAuthorizationRequest? The completion intent could be set to the same activity in app B (using singleTask), which can then setResult() and finish(). It's unclear to me whether app A even needs to see the AuthorizationResponse; if it does, it can be passed back as part of the result.

**Comment by Smao0875** [comment]
Hi @iainmcgin 
I think I fixed my problem yesterday.
Thanks for asking.
Maybe we should close this thread now.
Thanks for all the help!

**Comment by iainmcgin** [comment]
No problem, I'm glad you managed to get it working.

**Comment by gilangabdulaziz** [comment]
@Smao0875 I got same problem.. may I know how you solve this problem? thanks

**Comment by Smao0875** [comment]
I set the launchMode of my OAuthActivity which launches the authrequest to singleInstance.
My OAuthActivity is used to launch authrequest and handles the complete and cancel intent.

Does this help?
Thanks

**Comment by gilangabdulaziz** [comment]
@Smao0875 so it will be redirected to OAuthActivity itself?

**Comment by Smao0875** [comment]
@gilangabdulaziz 
Could you please show us your activity stack?
It would be easier.

Thanks

**Comment by gilangabdulaziz** [comment]
@Smao0875 
I'm following step-by-step implementation from wiki, seems AuthorizationManagementActivity not declared in manifest, but I'm not really sure is it manifest from library or the apps.. or maybe manifest merger failed :(

here's the Logcat

`FATAL EXCEPTION: main
                                                                               Process: com.example.geekseat.empsense, PID: 28486
                                                                               android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.geekseat.empsense/net.openid.appauth.AuthorizationManagementActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                                   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1837)
                                                                                   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
                                                                                   at android.app.Activity.startActivityForResult(Activity.java:4125)
                                                                                   at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                                   at android.app.Activity.startActivityForResult(Activity.java:4072)
                                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                                   at android.app.Activity.startActivity(Activity.java:4396)
                                                                                   at android.app.Activity.startActivity(Activity.java:4364)
                                                                                   at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:229)
                                                                                   at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:177)
                                                                                   at com.example.geekseat.empsense.MainActivity.makeAuthRequest(MainActivity.java:190)
                                                                                   at com.example.geekseat.empsense.MainActivity.access$100(MainActivity.java:52)
                                                                                   at com.example.geekseat.empsense.MainActivity$1.onFetchConfigurationCompleted(MainActivity.java:91)
                                                                                   at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:331)
                                                                                   at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:272)
                                                                                   at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                                   at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                                   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7007)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
`

**Comment by gilangabdulaziz** [comment]
@Smao0875 
Hi, I just solved this issue by adding AuthorizationManagementActivity to manifest :)

Thanks.
