### ISSUE TITLE
Android SDK 22: Service Intent must be explicit: Intent { act=android.support.customtabs.action.CustomTabsService }

### ISSUE THREAD

**Issue by deepakbhatia** [openid/AppAuth-Android#192]
I am trying to use the library for Authentication with Google Accounts.

I get the error mentioned in the title at the 
`            authorizationService = new AuthorizationService(context);
`

I tried this:

`Intent intent = new Intent("action");`
` intent.setPackage("android.support.customtabs.action.CustomTabsService"); `
` //intent.setpackage("net.openid.appauth.AuthorizationService");`
`bindService(intent, mConnection, Context.BIND_AUTO_CREATE);`

But onServiceConnected never gets called. So the authorizationService object is null

**Comment by iainmcgin** [comment]
Does the device you are testing on have a browser that supports custom tabs? If not, I possibly have a bug in the initialization code that attempts to connect to a custom tabs service.

**Comment by deepakbhatia** [comment]
The device, I was testing on, chrome was not updated. On update it worked.

**Comment by mujahid-sagoon** [comment]
Hello Everyone,

I am also getting crash logs for my app from crashlytics with the same reason on Android, 7, 6, 5 , specially on Galaxy J2(2016), SM-G610F,HUAWEI DLI-L42 devices.


Fatal Exception: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.support.customtabs.action.CustomTabsService }
       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1382)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1491)
       at android.app.ContextImpl.bindService(ContextImpl.java:1459)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:646)
       at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:71)
       at net.openid.appauth.BrowserHandler.bindCustomTabsService(BrowserHandler.java:86)
       at net.openid.appauth.BrowserHandler.(BrowserHandler.java:61)
       at net.openid.appauth.AuthorizationService.(AuthorizationService.java:101)
       at com.sagoon.connect.share.earn.Utils.AuthenticationManager.setContextActivity(AuthenticationManager.java:166)
       at com.sagoon.connect.share.earn.contacts.InviteFragment.onAttach(InviteFragment.java:140)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1363)
       at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
       at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
       at android.view.View.measure(View.java:19883)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:693)
       at android.view.View.measure(View.java:19883)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2317)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1408)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1661)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:623)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6205)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

I don't want to update chrome browser, i just want to resolved this issue independent of chrome version.
