### ISSUE TITLE
app crash on bad token response IllegalStateException JSONException 

### ISSUE THREAD

**Issue by Zhuoqing** [openid/AppAuth-Android#228]
This is caused by bad Authorization server, but the lib should not crash?

Version 0.6.0

The AuthorizationService is catching JSONException but the exception was wrapped to be IllegalStateException

FATAL EXCEPTION: main
java.lang.IllegalStateException: JSONException thrown in violation of contract
    at net.openid.appauth.TokenResponse$Builder.fromResponseJson(TokenResponse.java:235)
    at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:405)
    at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:306)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: org.json.JSONException: field "token_type" not found in json object
    at net.openid.appauth.JsonUtil.getString(JsonUtil.java:171)
    at net.openid.appauth.TokenResponse$Builder.fromResponseJson(TokenResponse.java:217)
    at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:405) 
    at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:306) 
    at android.os.AsyncTask.finish(AsyncTask.java:651) 
    at android.os.AsyncTask.-wrap1(AsyncTask.java) 
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by iainmcgin** [comment]
Do you know what the token response contained? I'll soften the error to an AuthorizationException regardless, but it would be useful to know what the JSON content of the response was that tripped up the library. Looking at the code, it's possible the response was missing a `token_type` field.

**Comment by Zhuoqing** [comment]
Yes the response was missing "token_type" and this is more a bug of the Authorization server.
Just a little surprised that this cause app to crash.

**Comment by iainmcgin** [comment]
Yep, that causing the library to throw an unchecked exception is a bug that I've now fixed. Sorry about that.
