### ISSUE TITLE
performAuthorizationRequest bug

### ISSUE THREAD

**Issue by Realague** [openid/AppAuth-Android#288]
Hello,

I use the 0.2.0 version of AppAuth-Android.

I get the following error when performing an authorization request on android 4.4.2.

```
10-26 17:51:19.719 3956-3956/io.payintech.tpe E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: io.payintech.tpe, PID: 3956
                                                                android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://keycloak-sandbox.payintech.io/auth/realms/station-ski/protocol/openid-connect/auth?redirect_uri=io.payintech.tpe://oauth2Callback&client_id=raclette-skiki&response_type=code&state=4LrlhIMSWLzChjXeejl7GA&scope=offline_access&code_challenge=5Zo5kE0aUK1dMNj_SXS75FYvHajLbs36GjEE2u5aRHU&code_challenge_method=S256 flg=0x40000000 (has extras) }
                                                                    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1638)
                                                                    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:3480)
                                                                    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:3432)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
                                                                    at android.app.Activity.startActivity(Activity.java:3683)
                                                                    at android.app.Activity.startActivity(Activity.java:3651)
                                                                    at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
                                                                    at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:170)
                                                                    at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:134)
                                                                    at io.payintech.tpe.activities.MainActivity$KeycloakAuthorizationListener.onClick(MainActivity.java:126)
                                                                    at android.view.View.performClick(View.java:4463)
                                                                    at android.view.View$PerformClick.run(View.java:18770)
                                                                    at android.os.Handler.handleCallback(Handler.java:808)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                    at dalvik.system.NativeStart.main(Native Method)
```

But when I use my app on the 5.0 or above version of android. It does works.

Hope you can help me.

**Comment by Realague** [comment]
I found the solution :)

Sorry for the bug tracker pollution :-p
