### ISSUE TITLE
Android 4.4.2 AppAuth exception when received the token

### ISSUE THREAD

**Issue by Realague** [openid/AppAuth-Android#291]
Hello everyone,

I'm using 'AppAuth' library to authentificate in Keycloak and it works in Android 6.0 but when I try in 4.4.2. I get this message of exception:
```
AuthorizationException: {"type":0,"errorDescription":"Network error","code":3}
                                                                    at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:305)
                                                                    at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:259)
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                 Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x60e18130: Failure in SSL library, usually a protocol error
                                                                error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x5db566ed:0x00000000)
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
                                                                    at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
                                                                    at com.android.okhttp.Connection.connect(Connection.java:107)
                                                                    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
                                                                    at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
                                                                    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
                                                                    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
                                                                    at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:296)
                                                                    	... 7 more
                                                                 Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x60e18130: Failure in SSL library, usually a protocol error
                                                                error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x5db566ed:0x00000000)
                                                                    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
                                                                    	... 17 more 
```

Can someone help me with this ?

**Comment by ruhijain** [comment]
Could you please let me know the solution for this? On Android 4.4, I also face some connection errors while using AppAuth.

**Comment by Barryrowe** [comment]
For anyone coming across this issue I want to share 2 things:

1) This particular issue has to do with TLSv1.2 support on older android versions, and there are a handful of solutions out there to make this part work.  This issue lead me down the path to getting past this particular problem:
https://github.com/square/okhttp/issues/2372#issuecomment-244807676

2) Once you're past this issue, you'll come to find that on API 16-19 (probably lower as well) `onActivityResult()` will fire immediately after you call `startActivityForResult` because AppAuth's authentication activity needs to use `launcheMode=singleInstance`. To my knowledge there's not a workaround for this particular issue. You can see more on #464
