### ISSUE TITLE
Json deserialisation error

### ISSUE THREAD

**Issue by antrikshkmr** [openid/AppAuth-Android#518]
I am using Squidex Identity Server to integrate with AppAuth.

Authorisation is successful using the endpoints but when the app has to request for token it throws an error:
/AppAuthSample: Token Exchange failed
    AuthorizationException: {"type":0,"code":5,"errorDescription":"JSON deserialization error"}
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:248)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:206)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONObject.<init>(JSONObject.java:168)
        at org.json.JSONObject.<init>(JSONObject.java:181)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:241)

The request works fine when checked on Postman. Any help would be appreciated.

**Comment by blundell** [comment]
Can you breakpoint it, and share here the exact JSON it is tryin to parse?

**Comment by PranjalDesai** [comment]
@antrikshkmr Did you find a solution for this?
@blundell I'm having a similar issue and I'm using synergy server. My response is coming "" but on postman, it works fine

**Comment by balkarov** [comment]
I had the same problem.
I am using IdentityServer4.
First i used the path to the server:
https://domain.com

But need use full path to config.
https://domain.com/.well-known/openid-configuration

**Comment by agologan** [comment]
@balkarov glad to hear it. 

There is a PR #612 that changes the config from asking **discoveryUri** to asking for **issuerUri** which will append the well-know path by itself making it easier to integrate.

**Comment by agologan** [comment]
Closing this as neither the OP or subsequent replies provided enough information to take action, in a reasonable amount of time. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
