### ISSUE TITLE
net.openid.appauth.AuthorizationManagementActivity NullPointerException

### ISSUE THREAD

**Issue by yinyerong** [openid/AppAuth-Android#576]
FATAL EXCEPTION: main
 java.lang.RuntimeException: Unable to resume activity {XXX/net.openid.appauth.AuthorizationManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4803)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4846)
 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:213)
 	at android.app.ActivityThread.main(ActivityThread.java:8201)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by santipg382s** [comment]
> FATAL EXCEPTION: main
> java.lang.RuntimeException: Unable to resume activity {XXX/net.openid.appauth.AuthorizationManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4803)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4846)
> at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401)
> at android.os.Handler.dispatchMessage(Handler.java:107)
> at android.os.Looper.loop(Looper.java:213)
> at android.app.ActivityThread.main(ActivityThread.java:8201)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by kamolsrisan** [comment]
good

**Comment by kamolsrisan** [comment]
good

**Comment by blundell** [comment]
Please create a Minimal Reproducible Example of the problem you are having, so others can validate/investigate.

**Comment by yinyerong** [comment]
> Please create a Minimal Reproducible Example of the problem you are having, so others can validate/investigate.

This is the Monkey test.
