### ISSUE TITLE
[Crashlytics] ActivityNotFoundException in AuthorizationService Class

### ISSUE THREAD

**Issue by shahfaizal** [openid/AppAuth-Android#648]
The Crash has been reported in crashlytics for latest PlayStore Version. Below are the crash logs form crashlytics for same. Attached the screenshot of crashlytics for reference.

Fatal Exception: android.content.ActivityNotFoundException
       at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:372)
       at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:232)
       at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:174)
       at com.janrain.android.engage.OpenIDAppAuthGoogle.makeAuthRequest(OpenIDAppAuthGoogle.java:162)
       at com.janrain.android.engage.OpenIDAppAuthGoogle.access$000(OpenIDAppAuthGoogle.java:62)
       at com.janrain.android.engage.OpenIDAppAuthGoogle$1.onFetchConfigurationCompleted(OpenIDAppAuthGoogle.java:120)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:364)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:305)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ghosalmartin** [comment]
you need to add the `<queries>` tag from the library manifest to your manifest since the 0.7.1 doesn't have it.

**Comment by agologan** [comment]
As @ghosalmartin mentioned if you're using version 0.7.1 or older you'll need to define `<queries>` tag manually.
Otherwise, please consider using a newer build from JitPack: https://jitpack.io/#openid/AppAuth-Android which resolves this issue.

**Comment by rwalbergpd** [comment]
We are experiencing something similar, using AppAuth 0.7.1. On Android 11, starting today (I believe), `BrowserSelector.getAllBrowsers()` is coming back with an empty list when it queries for `BROWSER_INTENT` intents. Android 10 and below is fine.

https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/browser/BrowserSelector.java#L90

We are pretty sure this was working yesterday (February 8th and earlier).

**Comment by rwalbergpd** [comment]
We added the `<queries>` section to our manifest and everything is fine. It only broke once we bumped the compile target from 29 to 30. 👍

**Comment by ghosalmartin** [comment]
@agologan Will there be an official release anytime soon with the latest fixes? Or is the precedent to now just use whatever commits we need and build vs that?

**Comment by chklch-pd** [comment]
@ghosalmartin take a look at  https://github.com/openid/AppAuth-Android/commit/41a6aa132fa45365aacd1c4b471ccf40670c884c.  There's readme instructions on what you need to add to your android manifest.

We're still using 0.7.1, just with our manifest defining what queries we will be using vs the library defining it.

**Comment by agologan** [comment]
As of today there is one: [0.8.0](https://search.maven.org/search?q=g:net.openid%20appauth)

**Comment by agologan** [comment]
In spite of the OP not responding, I'm assuming this was related to the `<queries>` tag and am closing the issue. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍
