### ISSUE TITLE
Nonce mismatch

### ISSUE THREAD

**Issue by Jawnnypoo** [openid/AppAuth-Android#650]
Since updating to `0.8.0`, the following error occurs when logging in with Google:

```
AuthorizationException: {"type":0,"code":9,"errorDescription":"Invalid ID Token"}
        at net.openid.appauth.IdToken.validate(IdToken.java:193)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:690)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:562)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: net.openid.appauth.IdToken$IdTokenException: Nonce mismatch
        at net.openid.appauth.IdToken.validate(IdToken.java:193) 
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:690) 
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:562) 
        at android.os.AsyncTask.finish(AsyncTask.java:755) 
        at android.os.AsyncTask.access$900(AsyncTask.java:192) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Updated from 0.7.1, made no other changes to the code. Any ideas?

**Comment by agologan** [comment]
The new version does include IdToken validation #385 
Have also ran our demo project against a newly created Google OAuth client ID and there are no issue as their servers correctly return the right nonce.

A mismatch in **nonce** usually means you are getting a replayed response which is not coming directly from the source and matching your request.
While there are security implications of a 3rd party replaying outdated/spoofed responses, it may just be that in your communication pathway (in app, or an intermediary server) there is a caching mechanism returning outdated responses.

_Alternatively if you do strongly believe there is problem with the lib please provide a working sample highlighting the issue._

**Comment by balkarov** [comment]
I have the same problem after update library to 0.8.0

**Comment by balkarov** [comment]
In my case problem occurs when i use IdentityServer on HTTP. On HTTPS works. But I need use both. I do not know why.
In descovery doc issuer with HTTP

**Comment by balkarov** [comment]
I think it because new version has this condition:
```java
Uri issuerUri = Uri.parse(this.issuer);

if (!issuerUri.getScheme().equals("https")) {
   throw AuthorizationException.fromTemplate(GeneralErrors.ID_TOKEN_VALIDATION_ERROR,
         new IdTokenException("Issuer must be an https URL"));
}
```

Do you have any workaround?

**Comment by carstenhag** [comment]
Please close this issue, as previously commented there are now ways to disable nonce & https verification checks

**Comment by agologan** [comment]
Details available in [README.md](https://github.com/openid/AppAuth-Android#issues-with-id-token-validation)
