### ISSUE TITLE
 ActivityNotFoundException in AuthorizationService Class

### ISSUE THREAD

**Issue by 33shashiranjan** [openid/AppAuth-Android#678]
### Checklist:

- [ ] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.7.1
- Integration: native(Java/Kotlin)
- Identity provider: Google

### Issue Description

We are using aapauth library version 0.7.1 for Google signin support. We have seen few crashes in appauth library.
Below is the Crashlytics log from user.
 
Fatal Exception: android.content.ActivityNotFoundException
       at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:372)
       at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:232)
       at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:174)
       at com.janrain.android.engage.OpenIDAppAuthGoogle.makeAuthRequest(OpenIDAppAuthGoogle.java:162)
       at com.janrain.android.engage.OpenIDAppAuthGoogle.access$000(OpenIDAppAuthGoogle.java:62)
       at com.janrain.android.engage.OpenIDAppAuthGoogle$1.onFetchConfigurationCompleted(OpenIDAppAuthGoogle.java:120)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:364)
       at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:305)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by agologan** [comment]
The checklist you are asked to fill in is not just for show.
**ActivityNotFoundException** could be either this https://github.com/openid/AppAuth-Android/issues/648 or https://github.com/openid/AppAuth-Android/issues/521 

_Closing this issue as duplicate. If this is not actually a duplicate please open a new issue explaining the difference between your issue and the existing ones._
