### ISSUE TITLE
JSON deserialization error if the server is unavailable

### ISSUE THREAD

**Issue by Melle010** [openid/AppAuth-Android#824]
### Configuration
- Version: 0.10.0
- Integration: native (Kotlin)
- Identity provider: Keycloak

### Description
If our Keycloak server is offline and returns e.g. `503 Service Unavailable`, then the `TokenResponseCallback` returns `AuthorizationException: {"type":0, "code":5, "errorDescription": "JSON deserialization error"}` instead of `AuthorizationException: {"type":0, "code":4, "errorDescription": "Server error"}`. This is because the body is not a JSON but a HTML. This is the log with the stacktrace:

```
    AuthorizationException: {"type":0,"code":5,"errorDescription":"JSON deserialization error"}
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:636)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:563)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONObject.<init>(JSONObject.java:172)
        at org.json.JSONObject.<init>(JSONObject.java:185)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:629)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:563) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
```

Since we want to intercept server errors (status codes 5xx) in our app, we need to know the exact exception. I think the JSON deserialization error is a general error and can also be returned for other status codes which is why we can't be 100% sure that this exception is caused by a server problem.

How do we know if the `AuthorizationException` was caused by a server problem and not some other error?

**Comment by schluderer** [comment]
Hello,

I have a similar issue due to a empty body. When I drop the connection with Proxyman or let it return a 503 there is an empty body which throws an JSON Exception at the end. It would be great if we could differentiate between those cases.
