### ISSUE TITLE
No browser found exception

### ISSUE THREAD

**Issue by evasyuk** [openid/AppAuth-Android#96]
If there is no browser at all user would get unexpected ActivityNotFoundException:

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=com.googleusercontent.apps.nope:/oauth2redirect&client_id=529788761403-aj9ff2svir6lsqjnck6jnjmqhfop77mk.apps.googleusercontent.com&response_type=code&state=Od4cn-XBtdi3Qdjnl5t7wg&scope=openid profile email&code_challenge=WJOmc7Hs3GcF0FpQ7dUJ3ISZxwETpkSmBods2dgMLr4&code_challenge_method=S256 flg=0x40000000 pkg=com.android.chrome (has extras) }
                                                                          at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1551)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1422)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3375)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3331)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
                                                                          at android.app.Activity.startActivity(Activity.java:3546)
                                                                          at android.app.Activity.startActivity(Activity.java:3514)
                                                                          at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:173)
                                                                          at net.openid.appauthdemo.MainActivity.makeAuthRequest(MainActivity.java:143)
                                                                          at net.openid.appauthdemo.MainActivity.access$100(MainActivity.java:54)
                                                                          at net.openid.appauthdemo.MainActivity$1.onFetchConfigurationCompleted(MainActivity.java:89)
                                                                          at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:325)
                                                                          at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:266)
                                                                          at android.os.AsyncTask.finish(AsyncTask.java:631)
                                                                          at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                          at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:153)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5022)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by iainmcgin** [comment]
It looks like we should immediately fire the provided pending intent with a failure if there is no browser.

**Comment by iainmcgin** [comment]
I have now formalized this behavior into the contract of performAuthorizationRequest as of 0.4.0 - if there is no browser available, ActivityNotFoundException will be thrown, and applications should be written to handle this (rare) eventuality.
